server:
  error.whitelabel.enabled: false
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /dota-bayes

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
      javax:
        persistence:
          query:
            timeout: 10000
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dota
    username: sa
    password: password
  banner:
    image:
      location: classpath:banner.png
      width: 100
      height: 15
      margin: 1
  h2:
    console:
      enabled: true

bayes:
  dota:
      damage-done-event-format: \[([0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3})] npc_dota_hero_([0-9a-zA-Z_]+) hits npc_dota_hero_([0-9a-zA-Z_]+) with ([0-9a-zA-Z_]+) for ([0-9]+) damage \([^)]*\)
      hero-killed-event-format: \[([0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3})] npc_dota_hero_([0-9a-zA-Z_]+) is killed by npc_dota_hero_([0-9a-zA-Z_]+)
      item-purchased-event-format: \[([0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3})] npc_dota_hero_([0-9a-zA-Z_]+) buys item item_([0-9a-zA-Z_]+)
      spell-cast-event-format: \[([0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3})] npc_dota_hero_([0-9a-zA-Z_]+) casts ability ([0-9a-zA-Z_]+) \(lvl ([0-9]+)\) on ([a-zA-Z_]+)


debug: false

logging:
  config: classpath:logback-${ENV:development}.xml
